# Generated by Django 3.0.3 on 2020-07-19 12:25

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0001_initial'),
    ]

    operations = [
         HStoreExtension(),
    ]
