# Generated by Django 3.0.3 on 2020-06-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='user_detail',
        ),
    ]
