# Generated by Django 3.0.3 on 2020-06-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0002_auto_20200630_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='contact_no',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
