# Generated by Django 3.0.3 on 2020-07-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0004_auto_20200702_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='designation',
            new_name='department',
        ),
    ]
