# Generated by Django 3.0.3 on 2020-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0005_auto_20200702_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=264)),
                ('full_name', models.CharField(max_length=264)),
                ('departmment', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
                ('contact_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('residential_status', models.CharField(max_length=264)),
            ],
        ),
    ]
