# Generated by Django 3.0.3 on 2020-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0006_staff_user_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_user_detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff_user_detail',
            name='emp_id',
            field=models.CharField(max_length=264, primary_key=True, serialize=False, unique=True),
        ),
    ]
