# Generated by Django 3.0.3 on 2020-07-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=15, unique=True)),
                ('mode', models.CharField(choices=[('SU', 'Student'), ('GU', 'General User')], default='SU', max_length=2)),
            ],
        ),
    ]
