# Generated by Django 3.0.3 on 2020-08-26 06:30

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorvisitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorsToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', django_mysql.models.JSONField(default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorvisitor.Doctor')),
            ],
        ),
    ]
